# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'select02' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for select02
  pod 'SwiftyJSON', '~> 2.3.2'
  pod 'AFNetworking', '~> 3.0'
  pod 'Fabric'
  # pod 'Answers'
  pod 'Crashlytics'
  pod 'Optimizely-iOS-SDK'

end
